name: Test on PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test infra
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2 
        with:
          python-version: 3.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: IaC Apply
        env:
          COMMAND_IAC: terraform 
        run: |
          cd infrastructure
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan